app:
  id: terminal-app
  name: terminal-app
  namespace: terminal-app

replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  name: terminal-app
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerPort: 8080

env: []

resources: {}

ingress:
  enabled: true
  name: terminal-app
  className: traefik
  host: ""
  path: /terminal
  pathType: Prefix
